[package]
name = "themes"
version = "0.1.0"
authors = ["Andrei Gherghescu andrei-ng@protonmail.com"]
edition = "2021"

[dependencies]
ndarray = "0.17"
csv = "1.1"
plotly = { path = "../../plotly" }
plotly_utils = { path = "../plotly_utils" }
