[package]
name = "statistical-charts"
version = "0.1.0"
authors = ["Michael Freeborn <michaelfreeborn1@gmail.com>"]
edition = "2021"

[dependencies]
ndarray = "0.16"
plotly = { path = "../../plotly" }
plotly_utils = { path = "../plotly_utils" }
rand = "0.9"
rand_distr = "0.5"
