[package]
name = "customization"
version = "0.1.0"
authors = ["Andrei Gherghescu andrei-ng@protonmail.com"]
edition = "2021"

[dependencies]
build_html = "2.5.0"
rand = "0.9"
ndarray = "0.16"
plotly = { path = "../../plotly" }
plotly_utils = { path = "../plotly_utils" }
