[package]
name = "shapes"
version = "0.1.0"
authors = ["Michael Freeborn <michaelfreeborn1@gmail.com>"]
edition = "2021"

[dependencies]
ndarray = "0.15.6"
plotly = { path = "../../plotly" }
rand = "0.8.5"
rand_distr = "0.4.3"
